# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 698a8d5f735d06d136d314606c92b288e0f4270350bc375b3c401cfeffd5754a274690257f17b27b3456b0bcbb5a566d26232af499db2fc1eeaa4bb4004c7323

test:
  secret_key_base: b97a971e26b30196b69bff7b242fe9b38c01f88ea69ba8a7f2721591f87515c3e9bfe8372f717eebcc0f19c0346c17e9936caabeeb99f1c38ffd395f867048f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
